# Generated by Django 4.0.4 on 2022-05-23 17:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator])),
                ('guest', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator])),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator])),
                ('image_local', models.ImageField(blank=True, null=True, upload_to='photo_images_gallery')),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator])),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator])),
            ],
        ),
        migrations.CreateModel(
            name='PromoEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator])),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator])),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_date', models.DateField()),
                ('end_time', models.TimeField()),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, validators=[django.core.validators.MinLengthValidator])),
                ('price', models.IntegerField()),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator])),
                ('image_url', models.URLField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.productcategory')),
            ],
        ),
    ]
