# Generated by Django 4.0.4 on 2022-05-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_event_created_on_photogallery_created_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photogallery',
            name='image_url',
        ),
        migrations.AddField(
            model_name='photogallery',
            name='cover_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='photogallery',
            name='image_local',
            field=models.ImageField(default=1, upload_to='photo_images_gallery'),
            preserve_default=False,
        ),
    ]
