# Generated by Django 4.0.4 on 2022-05-27 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_photogallery_image_url_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PhotoGallery',
            new_name='Photos',
        ),
    ]
